# Generated by Django 2.1.3 on 2018-11-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_author_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='name',
            new_name='artical_author',
        ),
    ]
